set(SIMROBOTCOMMON_ROOT_DIR "${PROJECT_SOURCE_DIR}/Src/SimRobotCommon")

file(GLOB_RECURSE SIMROBOTCOMMON_SOURCES CONFIGURE_DEPENDS
    "${SIMROBOTCOMMON_ROOT_DIR}/*.cpp" "${SIMROBOTCOMMON_ROOT_DIR}/*.h")

add_library(SimRobotCommon STATIC EXCLUDE_FROM_ALL ${SIMROBOTCOMMON_SOURCES})
set_property(TARGET SimRobotCommon PROPERTY POSITION_INDEPENDENT_CODE ON)
target_include_directories(SimRobotCommon PUBLIC "${SIMROBOTCOMMON_ROOT_DIR}")
target_link_libraries(SimRobotCommon PUBLIC Eigen3::Eigen)
